Repository redis/redis-om-python, pull requests merged in 2022-08, with the labels that each got.

#282 Updating default page size to 1000 from 10
  aredis_om/model/model.py
Labels: bug, breakingchange

#337 fixed a potential bug
  aredis_om/model/model.py
  pyproject.toml
  tests/test_hash_model.py
Labels: bug

#305 Add `delete_many` to support for bulk deletes
  aredis_om/model/model.py
  poetry.lock
  pyproject.toml
  tests/test_hash_model.py
  tests/test_json_model.py
Labels: enhancement

#341 Updating troves for pypi
  pyproject.toml
Labels: maintenance

#346 Replace `execute_command` with specific redis functions when possible
  aredis_om/model/migrations/migrator.py
  aredis_om/model/model.py
  tests/test_json_model.py
Labels: maintenance
