Repository redis/redis-om-python, pull requests merged in 2022-09, with the labels that each got.

#362 fix repository url
  pyproject.toml
Labels: maintenance

#374 Drop python 3.6 support
  .github/workflows/ci.yml
  pyproject.toml
Labels: maintenance, breakingchange

#368 Fix None instance when querying
  aredis_om/model/model.py
Labels: bug

#373 Fixes issue decode_responses is set to True regardless if REDIS_OM_UR…
  aredis_om/connections.py
Labels: maintenance

#348 fix broken links
  README.md
  aredis_om/model/token_escaper.py
  docs/getting_started.md
  docs/redis_modules.md
Labels: maintenance

#347 Allow users to define a new primary key.
  aredis_om/model/model.py
  tests/test_hash_model.py
Labels: enhancement

#376 fix: add slash in DEFAULT_ESCAPED_CHARS (#312)
  aredis_om/model/token_escaper.py
Labels: bug

#372 Fix crash when trying to delete non-existent record
  aredis_om/model/model.py
  tests/test_hash_model.py
Labels: bug
