Repository redis/redis-om-python, pull requests merged in 2024-05, with the labels that each got.

#603 Refactoring Redis OM Python to use pydantic 2.0 types and validators
  README.md
  aredis_om/_compat.py
  aredis_om/model/encoders.py
  aredis_om/model/model.py
  pyproject.toml
  tests/_compat.py
  tests/test_hash_model.py
  tests/test_json_model.py
  tests/test_oss_redis_features.py
Labels: enhancement, breakingchange

#611 adding support for boolean checks
  Makefile
  aredis_om/model/model.py
  docs/getting_started.md
  tests/test_json_model.py
Labels: bug

#614 fixing issue with breaking typing.Dict in JsonModel
  aredis_om/model/model.py
  tests/test_json_model.py
Labels: bug

#616 fixing None types in hashes
  aredis_om/model/model.py
  tests/test_hash_model.py
  tests/test_json_model.py
Labels: bug

#573 Update models.md
  docs/models.md
Labels: documentation
